resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/riteshbabu/concourse-demo.git
      branch: master

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
#  - task: install
 #   file: sources/pipeline/install.yml
  - task: test
     run:
      path: echo
      args: ["Hello, world!"]
    file: sources/pipeline/test.yml
